### ISSUE TITLE
Dúvida sobre a instalação da Calculadora

### ISSUE THREAD

**Issue by guiaparicio** [EduardoMMorais/BDMarcapasso#7]
Olá @EduardoMMorais, 

Estou tentando realizar a instalação da Calculadora no Docker. 

Segui todos os passos com sucesso, porém ao acessar a aplicação via navegador carrega apenas a tela inicial do nginx.

Sabe me dizer se existe alguma configuração adicional pendente? Desde já muito obrigado.

Obs: Cheguei no seu projeto por indicação da Kátia (REDCap Brasil)

**Comment by EduardoMMorais** [comment]
Desculpe, acho que eu deve ter algum erro na configuração do nginx
O endereço http://localhost/index.html te leva para o lugar certo?
Se não funcionar, por favor verifique se ao menos http://localhost/model/variables.html existem

**Comment by guiaparicio** [comment]
Implementei na minha máquina (usando o localhost) e funcionou perfeitamente. 

O problema aparentemente ocorre quando vou acessar através do ambiente na nuvem (AWS), onde o padrão de URL não será http://localhost

**Comment by EduardoMMorais** [comment]
O que acontece quando você insere a URL da sua instância AWS? Algum erro? Alguma mensagem?
Se houver algum problema com a configuração no AWS poderei testar em uma conta AWS real até o fim da semana

**Comment by guiaparicio** [comment]
Quando acesso a URL da instancia (Porta 80 liberada) é exibido a tela de boa vindas do Ngnix.

Acredito que talvez tenha que ser configurado o server name da aplicação, mas confesso que não sei como fazer isso em um container Docker.

Obs: Se eu acesso a instancia via SSH e e dou um:

```ssh

curl -s localhost:80

```

É retorno o formulário da aplicação, por isso acredito ser algo relacionado ao server name no ngnix

**Comment by EduardoMMorais** [comment]
> Quando acesso a URL da instancia (Porta 80 liberada) é exibido a tela de boa vindas do Ngnix.
Acredito que é o mesmo problema do localhost. Provavelmente usando http://<url da instância>/index.html deve funcionar. Se puder, podr favor teste.
Mas vamos rever a configuração do Ngnix para resolver esses problemas

**Comment by guiaparicio** [comment]
**Acredito que é o mesmo problema do localhost. Provavelmente usando http://<url da instância>/index.html deve funcionar.**
Não funciona, segue a URL: http://ec2-34-231-19-216.compute-1.amazonaws.com

**Comment by EduardoMMorais** [comment]
Criei um novo release que deve resolver. Pode criar um novo container com esse release e testar?
https://github.com/EduardoMMorais/BDMarcapasso/releases/tag/beta-0.10

**Comment by guiaparicio** [comment]
Instalei o novo release, porém ainda não obtive sucesso. (Segui o mesmo processo de instalação da versão 0.9)

![image](https://user-images.githubusercontent.com/6039684/194858475-159e3764-43e5-49da-a32d-e81bc8ad1663.png)

URL AWS:
http://ec2-34-231-19-216.compute-1.amazonaws.com/

**Comment by EduardoMMorais** [comment]
Não sei o que pode ser. Apenas imagino que exista algum problema na configuração do AWS.
Me contate por e-mail e podemos marcar de ver isso juntos online pra encontrar o problema

**Comment by guiaparicio** [comment]
Acho que consegui fazer funcionar, segue os passos:

1 - Segui a instalação como na doc do release.

2 - Acessei o container via terminal: 

```ssh

docker exec -t -i calculadora /bin/bash

```

3 - Instalei o nano no container

```ssh

apt-get install nano

```

4 - Acessei o arquivo de configuração do Ngnix

```ssh

nano /etc/nginx/conf.d/default.conf

```

5 - Modifiquei a linha:

```ssh

# server_name  localhost "";
server_name <URL_AWS>;

```

6 - Sai do terminal do container, e dei um reload no ngnix:

```ssh

docker exec calculadora nginx -s reload

```

Não sei se é o jeito correto de fazer essa configuração, mas aparentemente funcionou

**Comment by EduardoMMorais** [comment]
Ok, agora acho encontrei o problema mesmo.
Não deveria ser necessário especificar o server_name pois esse deveria ser o servidor padrão do nginx, que ele apresenta se não bater com nenhum hostname.
Porém não tinha visto que o pacote do debian cria um outro servidor em `/etc/nginx/sites-enabled/default` e este estava sendo usado como padrão ao invés do nosso.
A versão 0.11 (https://github.com/EduardoMMorais/BDMarcapasso/releases/tag/beta-0.11) remove esse arquivo e agora o não deve ter mais problemas com hostname.
Obrigado pela paciência
